"""digest table

Revision ID: 0b10a2aa1e04
Revises: de033880e991
Create Date: 2026-09-02 23:52:58.259385
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '0b10a2aa1e04'
down_revision: str | None = 'de033880e991'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digest_run_id'))

    op.drop_table('digest')
    # ### end Alembic commands ###
