"""initial schema

Revision ID: 1544e2799ea9
Revises: 
Create Date: 2026-09-02 20:37:08.629743
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '1544e2799ea9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_auth',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passphrase_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_lat', sa.Float(), nullable=True),
    sa.Column('target_lon', sa.Float(), nullable=True),
    sa.Column('radius_km', sa.Integer(), nullable=False),
    sa.Column('allow_remote', sa.Boolean(), nullable=False),
    sa.Column('target_fields', sa.JSON(), nullable=True),
    sa.Column('target_titles', sa.JSON(), nullable=True),
    sa.Column('keywords_allow', sa.JSON(), nullable=True),
    sa.Column('keywords_block', sa.JSON(), nullable=True),
    sa.Column('job_types', sa.JSON(), nullable=True),
    sa.Column('recency_days', sa.Integer(), nullable=False),
    sa.Column('language_max_cefr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language_hard', sa.Boolean(), nullable=False),
    sa.Column('hours_max', sa.Integer(), nullable=False),
    sa.Column('hours_hard', sa.Boolean(), nullable=False),
    sa.Column('contract_types', sa.JSON(), nullable=True),
    sa.Column('contract_type_hard', sa.Boolean(), nullable=False),
    sa.Column('score_threshold_recommend', sa.Integer(), nullable=False),
    sa.Column('score_threshold_maybe', sa.Integer(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('blend_soft_ratio', sa.Float(), nullable=False),
    sa.Column('run_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notify_channels', sa.JSON(), nullable=True),
    sa.Column('notify_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notify_telegram_chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('digest_top_n', sa.Integer(), nullable=False),
    sa.Column('cover_letter_language_mode', sa.Enum('MATCH_POSTING', 'ALWAYS_DE', 'ALWAYS_EN', name='coverletterlanguagemode'), nullable=False),
    sa.Column('cover_letter_tone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sources_enabled', sa.JSON(), nullable=True),
    sa.Column('eligibility_module_enabled', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('repost_days', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ats_type', sa.Enum('GREENHOUSE', 'LEVER', 'PERSONIO', 'SMARTRECRUITERS', 'ASHBY', 'NONE', name='atstype'), nullable=False),
    sa.Column('ats_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('careers_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.Enum('SEED', 'USER', 'DISCOVERED', name='companyorigin'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('profile',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_eu_eea', sa.Boolean(), nullable=False),
    sa.Column('university', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('program', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('degree_level', sa.Enum('BACHELOR', 'MASTER', 'PHD', name='degreelevel'), nullable=True),
    sa.Column('current_semester', sa.Integer(), nullable=True),
    sa.Column('enrollment_valid_until', sa.Date(), nullable=True),
    sa.Column('expected_graduation', sa.Date(), nullable=True),
    sa.Column('cv_document_id', sa.Integer(), nullable=True),
    sa.Column('structured_json', sa.JSON(), nullable=True),
    sa.Column('locked_fields', sa.JSON(), nullable=True),
    sa.Column('voice_sample_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.Enum('SCHEDULE', 'MANUAL', name='runtrigger'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_eur', sa.Float(), nullable=False),
    sa.Column('budget_exhausted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CV', 'ENROLLMENT', 'TRANSCRIPT', 'REFERENCE', 'PORTFOLIO', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('parse_status', sa.Enum('PENDING', 'DONE', 'FAILED', name='parsestatus'), nullable=False),
    sa.Column('parse_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_profile_id'), ['profile_id'], unique=False)

    op.create_table('job',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_job_id', sa.Integer(), nullable=True),
    sa.Column('source_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apply_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_run_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('lifecycle', sa.Enum('ACTIVE', 'STALE', 'DEAD', name='joblifecycle'), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('jd_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jd_content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('salary_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['first_seen_run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', 'source_job_id', name='uq_job_source')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_canonical_job_id'), ['canonical_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_jd_content_hash'), ['jd_content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_normalized_title'), ['normalized_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_source_key'), ['source_key'], unique=False)

    op.create_table('llm_call',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Enum('PROFILE_PARSE', 'KEYWORD_SUGGEST', 'ANALYZE', 'JUDGE', 'COVER_LETTER', name='llmpurpose'), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_eur', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_call', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_run_id'), ['run_id'], unique=False)

    op.create_table('pipeline_run',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OK', 'PARTIAL', 'FAILED', 'SKIPPED', name='pipelinestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_run_run_id'), ['run_id'], unique=False)

    op.create_table('profile_skill',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('LANGUAGE', 'TECHNICAL', 'TOOL', 'DOMAIN', 'SOFT', name='skillcategory'), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=False),
    sa.Column('years', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_skill_profile_id'), ['profile_id'], unique=False)

    op.create_table('semester_term',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lecture_start', sa.Date(), nullable=False),
    sa.Column('lecture_end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semester_term', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semester_term_profile_id'), ['profile_id'], unique=False)

    op.create_table('application',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INTERESTED', 'PREPARING', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('documents_used', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_job_id'), ['job_id'], unique=True)

    op.create_table('eligibility_entry',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('day_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_count', sa.Float(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_entry_profile_id'), ['profile_id'], unique=False)

    op.create_table('job_analysis',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('analyzer_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('must_haves', sa.JSON(), nullable=True),
    sa.Column('nice_haves', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('weekly_hours', sa.Integer(), nullable=True),
    sa.Column('weekly_hours_basis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contract_type', sa.Enum('WERKSTUDENT', 'PRAKTIKUM', 'THESIS', 'MINIJOB', 'PART_TIME', 'FULL_TIME', 'UNKNOWN', name='contracttype'), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('salary_period', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('enrollment_required', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('english_only', sa.Boolean(), nullable=False),
    sa.Column('application_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('documents_requested', sa.JSON(), nullable=True),
    sa.Column('seniority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_resolved', sa.JSON(), nullable=True),
    sa.Column('red_flags', sa.JSON(), nullable=True),
    sa.Column('source_snippets', sa.JSON(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('parse_failed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'analyzer_version', name='uq_analysis_job_version')
    )
    with op.batch_alter_table('job_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_analysis_job_id'), ['job_id'], unique=False)

    op.create_table('job_embedding',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('job_score',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('hard_pass', sa.Boolean(), nullable=False),
    sa.Column('hard_failures', sa.JSON(), nullable=True),
    sa.Column('soft_score', sa.Float(), nullable=False),
    sa.Column('soft_breakdown', sa.JSON(), nullable=True),
    sa.Column('llm_holistic', sa.Float(), nullable=True),
    sa.Column('llm_rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('missing_qualifications', sa.JSON(), nullable=True),
    sa.Column('strengths_to_highlight', sa.JSON(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('RECOMMENDED', 'MAYBE', 'ARCHIVED', name='decision'), nullable=False),
    sa.Column('documents_needed', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_score_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_score_run_id'), ['run_id'], unique=False)

    op.create_table('cover_letter',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('claims_used', sa.JSON(), nullable=True),
    sa.Column('docx_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cover_letter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cover_letter_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover_letter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cover_letter_job_id'))

    op.drop_table('cover_letter')
    with op.batch_alter_table('job_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_score_run_id'))
        batch_op.drop_index(batch_op.f('ix_job_score_job_id'))

    op.drop_table('job_score')
    op.drop_table('job_embedding')
    with op.batch_alter_table('job_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_analysis_job_id'))

    op.drop_table('job_analysis')
    with op.batch_alter_table('eligibility_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_entry_profile_id'))

    op.drop_table('eligibility_entry')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_job_id'))

    op.drop_table('application')
    with op.batch_alter_table('semester_term', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semester_term_profile_id'))

    op.drop_table('semester_term')
    with op.batch_alter_table('profile_skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_skill_profile_id'))

    op.drop_table('profile_skill')
    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_run_run_id'))

    op.drop_table('pipeline_run')
    with op.batch_alter_table('llm_call', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_run_id'))

    op.drop_table('llm_call')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_source_key'))
        batch_op.drop_index(batch_op.f('ix_job_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_job_jd_content_hash'))
        batch_op.drop_index(batch_op.f('ix_job_company_id'))
        batch_op.drop_index(batch_op.f('ix_job_canonical_job_id'))

    op.drop_table('job')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_profile_id'))

    op.drop_table('document')
    op.drop_table('run')
    op.drop_table('profile')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_normalized_name'))

    op.drop_table('company')
    op.drop_table('app_settings')
    op.drop_table('app_auth')
    # ### end Alembic commands ###
