"""job feedback

Revision ID: 4a07427937c2
Revises: 0b10a2aa1e04
Create Date: 2026-09-03 00:38:21.173860
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


revision: str = '4a07427937c2'
down_revision: str | None = '0b10a2aa1e04'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_feedback',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_feedback_job_id'), ['job_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_feedback_job_id'))

    op.drop_table('job_feedback')
    # ### end Alembic commands ###
